### PR TITLE
Refactor and fix #8

### LINKED ISSUE #8: Only look for input elements with the name attribute in the same form

### PR DESCRIPTION
**Pull request by zhouzi**
Hello!

Here's basically what' I've done:
- Added `.editorconfig` to respect your editor configuration
- Added gulp to produce the minified version
- Refactored (i.e simplified some selectors, loops)
- Added support for [`data-`attributes](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Using_data_attributes), which is the recommended way to deal with custom attributes
- Fixed #8 by getting the inputs within the same form
- Added a basic html file to test all this stuff

### CODE REVIEW

**Comment by bookercodes** [comment]
Many thanks for your contribution, @Zhouzi.

I will review this now.

**Comment by bookercodes** [comment]
I am really pleased with these changes. Thanks again, @Zhouzi - great work!

Hopefully you understand, but I decided not to include a build system like Gulp at this time.

**Comment by zhouzi** [comment]
No problem! I didn't know that we could invalidate a form "natively".

**Comment by bookercodes** [comment]
What do you mean?

**Comment by zhouzi** [comment]
I meant that thanks to your repository I learned that we can "natively" invalidate a form so thank you! :)

**Comment by bookercodes** [comment]
Oh, right. No problem.

**Pull request closed without merging**
