### PR TITLE
spinal-case for attributes

### PR DESCRIPTION
**Pull request by kana-sama**

### CODE REVIEW

**Comment by bookercodes** [comment]
Hello, @e-andrew. 

I am not really sure why you think this is needed...? 

I will be happy to consider this if you can make a compelling argument.

**Comment by TrySound** [comment]
@alexbooker Take a look at dataset API. It uses spinal case and converts to camelCase.
But I would like to write `compare` or `data-compare`

**Comment by kana-sama** [comment]
Because it is standard. And when I see compareTo in my html-code, my eyes begin to flow.

**Comment by TrySound** [comment]
@e-andrew I think all html code must be lowercase. But it's me. So you have a chance to make both of us happy ;)

**Comment by bookercodes** [comment]
How could I say no? :blush:

Many thanks, @e-andrew. I merged your other pull request too.

**Comment by TrySound** [comment]
@alexbooker  Thanks!

**Comment by kana-sama** [comment]
@alexbooker thanks)

**Pull request merged**
